# fly.toml app configuration file generated for opencomms-rendezvous on 2026-04-30T23:09:11-04:00
app = 'opencomms-rendezvous'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  OPENCOMMS_RENDEZVOUS_BIND = '0.0.0.0'

[http_service]
  internal_port = 8788
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
